// Generated by https://quicktype.io
export var Size;
(function (Size) {
    Size["Extralarge"] = "extralarge";
    Size["Large"] = "large";
    Size["Medium"] = "medium";
    Size["Mega"] = "mega";
    Size["Small"] = "small";
})(Size || (Size = {}));
